baseurl: '/'
permalink: pretty
title: 'Blue Course Community Church'

logo:
  mobile: "images/BCCC_FullLogo.PNG"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/bccc_namelogo_cropped.png"
  desktop_height: "70px"
  desktop_width: "240px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
